[2025-03-23T04:39:42.145+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: recolectar_datos_api.extraer_datos manual__2025-03-23T04:39:39.562398+00:00 [queued]>
[2025-03-23T04:39:42.167+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: recolectar_datos_api.extraer_datos manual__2025-03-23T04:39:39.562398+00:00 [queued]>
[2025-03-23T04:39:42.168+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-03-23T04:39:42.190+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): extraer_datos> on 2025-03-23 04:39:39.562398+00:00
[2025-03-23T04:39:42.219+0000] {standard_task_runner.py:57} INFO - Started process 100 to run task
[2025-03-23T04:39:42.235+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'recolectar_datos_api', 'extraer_datos', 'manual__2025-03-23T04:39:39.562398+00:00', '--job-id', '39', '--raw', '--subdir', 'DAGS_FOLDER/recolectar_datos.py', '--cfg-path', '/tmp/tmpq9neipjg']
[2025-03-23T04:39:42.237+0000] {standard_task_runner.py:85} INFO - Job 39: Subtask extraer_datos
[2025-03-23T04:39:42.443+0000] {task_command.py:415} INFO - Running <TaskInstance: recolectar_datos_api.extraer_datos manual__2025-03-23T04:39:39.562398+00:00 [running]> on host 37b147adca64
[2025-03-23T04:39:42.723+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='recolectar_datos_api' AIRFLOW_CTX_TASK_ID='extraer_datos' AIRFLOW_CTX_EXECUTION_DATE='2025-03-23T04:39:39.562398+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-23T04:39:39.562398+00:00'
[2025-03-23T04:39:43.397+0000] {logging_mixin.py:151} INFO - Lote 8 guardado en /opt/***/datos_raw/lote_8.json
[2025-03-23T04:39:43.401+0000] {python.py:194} INFO - Done. Returned value was: None
[2025-03-23T04:39:43.436+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=recolectar_datos_api, task_id=extraer_datos, execution_date=20250323T043939, start_date=20250323T043942, end_date=20250323T043943
[2025-03-23T04:39:43.560+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-03-23T04:39:43.616+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
